<?php
/**
 * @file
 * Code for the CWI CT Person feature.
 */

include_once('ct_person.features.inc');

function  ct_person_generate_title($node) {
  $prefix = '';

  if (count($node->field_person_prefix) && count($node->field_person_prefix['und'])) {
    $prefix  .= $node->field_person_prefix['und'][0]['value'];
  } 
  return $prefix . " " . $node->field_person_namefirst['und'][0]['value'] ." " . $node->field_person_namelast['und'][0]['value'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ct_person_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'person_node_form') {
    $form['menu']['#access'] = FALSE;
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function ct_person_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    $group = $implementations['ct_person'];
    unset($implementations['ct_person']);
    $implementations['ct_person'] = $group;
  }
}
